language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
  homebrew:
    taps:
      - facebook/fb
    packages: 
      - buck

jdk:
  - openjdk8

os:
  - linux
  - osx

osx_image: xcode9.3

before_install:
- ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
- ./buckaroo-portable install
- buck build :satori -c ui.superconsole=DISABLED
# - buck test satori/tests:inflate-deflate-tests -c ui.superconsole=DISABLED
# - buck test satori/tests:managed-ptr-tests -c ui.superconsole=DISABLED
# - buck test satori/tests:router-tests -c ui.superconsole=DISABLED
# - buck test satori/tests:url-parser-tests -c ui.superconsole=DISABLED
# - buck test satori/tests:url-encode-tests -c ui.superconsole=DISABLED
