cxx_test(
  name = 'managed-ptr-tests',
  srcs = [
    'managedPtrTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'router-tests',
  srcs = [
    'routerTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'url-parser-tests',
  srcs = [
    'urlParserTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'url-encode-tests',
  srcs = [
    'urlEncodeTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'inflate-deflate-tests',
  srcs = [
    'inflateDeflateTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)


cxx_test(
  name = 'stringview-tests',
  srcs = [
    'stringviewTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)
