cxx_test(
  name = 'managed-ptr-tests',
  srcs = [
    'managed_ptr_tests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'router-tests',
  srcs = [
    'router-tests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'url-parser-tests',
  srcs = [
    'url-parser-tests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'url-encode-tests',
  srcs = [
    'urlEncodeTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)

cxx_test(
  name = 'inflate-deflate-tests',
  srcs = [
    'inflateDeflateTests.cpp',
  ],
  deps = [
    '//:satori',
  ],
)
